#add_newline = false

#[line_break]
#disabled = true

[aws]
style = "bg:#f9a600 fg:black"
symbol = "ï™¢ "
format = "[î‚°](fg:black bg:#f9a600)[$symbol$profile]($style)[î‚°](fg:#f9a600 bg:black)"

[character]
success_symbol = "[â¯](#ff9400)"
error_symbol = "[âœ—](#ff4b00)"

[cmd_duration]
style = "#f9a600"
format = "[î‚°](fg:black bg:#f9a600)[ï¨š$duration](bg:$style fg:black)[î‚°](fg:$style)"

[custom.git_status_return]
format = "\b\b[î‚°](fg:#c05303)"
when = "git st 2>/dev/null; test $status -ne 0"

[directory]
style = "#c05303"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[î‚°](fg:black bg:#c05303)[$path[$read_only]($read_only_style)](bg:$style fg:black)[î‚°](fg:$style)"

[docker_context]
style = "fg:black bg:#eb9606"
symbol = "ğŸ³  "
format = "[î‚°](fg:black bg:#eb9606)[$symbol$context]($style)[î‚°](fg:#eb9606)"

[git_branch]
style = "#d8712c"
format = "[î‚°](fg:black bg:$style)[ $symbol$branch](fg:black bg:$style)[î‚°](fg:$style)"

[git_state]
style = "#d8712c"
format = "\b\b[ \\($state( $progress_current/$progress_total)\\)](fg:white bg:$style)[î‚°](fg:$style)"

[git_status]
style = "#d8712c"
format = "\b[ ](bg:$style)($conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind\b)[î‚°](fg:$style)"
conflicted = "[ îƒ‡ ](fg:88)[ î€‰ ï‘€ ${count} ](fg:white)[îƒ† ](fg:88)"
staged = "[ï§ $count ](fg:black bg:#d8712c)"
modified = "[ï£ª ${count} ](fg:black bg:#d8712c)"
renamed = "[ï€« ${count} ](fg:black bg:#d8712c)"
deleted = "[ï€” ${count} ](fg:black bg:#d8712c)"
untracked = "[?${count} ](fg:black bg:#d8712c)"
stashed = "[ï’‡ ${count} ](fg:black bg:#d8712c)"
ahead = "[ ïƒ® ${count} ](fg:purple bg:#d8712c)"
behind = "[ ïƒ­ ${count} ](fg:yellow bg:#d8712c)"
diverged = "[ îƒ‡](fg:88)[ î€‰ ï­€ ](fg:white bg:88)[ïƒ® ${ahead_count} ](fg:purple)[ïƒ­ ${behind_count} ](fg:yellow)[îƒ† ](fg:88)"

[golang]
symbol = "ï³‘ "
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version]($style)[î‚°](fg:#eb9606)"

[helm]
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol($version)]($style)[î‚°](fg:#eb9606)"

[java]
symbol = "ïƒ´ "
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version]($style)[î‚°](fg:#eb9606)"

[kotlin]
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version]($style)[î‚°](fg:#eb9606)"

[kubernetes]
format = "[î‚°](fg:black bg:#ad4007)[$symbol$context](fg:black bg:#ad4007)[î‚°](fg:#ad4007)"
disabled = false

#[memory_usage]
#style = "#f9a600"
#symbol = "ï™ "
#format = "[î‚°](fg:black bg:#f9a600)[$symbol$ram](bg:$style fg:black)[î‚°](fg:$style)"
#threshold = 95
#disabled = false

[nodejs]
style = "green"
format = "[î‚°](fg:black bg:#eb9606)[$symbol($version)](fg:black bg:#eb9606)[î‚°](fg:#eb9606)"

[ocaml]
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version]($style)[î‚°](fg:#eb9606)"

[package]
disabled = true

[php]
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version]($style)[î‚°](fg:#eb9606)"

[python]
symbol = "ï   "
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$pyenv_prefix$version$virtualenv]($style)[î‚°](fg:#eb9606)"

[ruby]
symbol = "îˆ "
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version](fg:black bg:#eb9606)(fg:black bg:#eb9606)[î‚°](fg:#eb9606)"

[rust]
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version]($style)[î‚°](fg:#eb9606)"

[scala]
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version]($style)[î‚°](fg:#eb9606)"

[swift]
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version]($style)[î‚°](fg:#eb9606)"

[shlvl]
symbol = "ï• "
style = "fg:black bg:#ad4007"
format = "[î‚°](fg:black bg:#ad4007)[$symbol$shlvl]($style)[î‚°](fg:#ad4007)"
disabled = false

[terraform]
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$workspace]($style)[î‚°](fg:#eb9606)"

[vagrant]
style = "fg:black bg:#eb9606"
format = "[î‚°](fg:black bg:#eb9606)[$symbol$version]($style)[î‚°](fg:#eb9606)"